
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author
 */
public class GuiMVM extends javax.swing.JFrame {

    private static short memParm[];
    private String[] args;
    CpuMVM _cpuMVM;
    MemoriaMVM _memMVM;
    BiosMVM _biosMVM;

    /**
     * Creates new form Botao
     */
    public GuiMVM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelEscolhaPrograma = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeroPrograma = new javax.swing.JTextField();
        jButtonExecutar = new javax.swing.JButton();
        jPanelTraces = new javax.swing.JPanel();
        jCheckBoxTraceBusca = new javax.swing.JCheckBox();
        jCheckBoxTraceDecodificaExecuta = new javax.swing.JCheckBox();
        jCheckBoxDumpMemoria = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBoxDumpPilha = new javax.swing.JCheckBox();
        jPanelConfig = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEnderecoCarga = new javax.swing.JTextField();
        jPanelPlacaVideo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMonitor = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanelHabilitaInterrupcoes = new javax.swing.JPanel();
        jCheckBoxInterrupcoesHabilitadas = new javax.swing.JCheckBox();
        jPanelMaximoNumeroInstrucoes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaxNumInstrucoes = new javax.swing.JTextField();
        jPanelEnderecoCarga = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaTrace = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mattos Virtual Machine");
        setBounds(new java.awt.Rectangle(0, 0, 500, 0));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CPU MVM"));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 500));
        //cria a cpu e a memoria da MVM
        _cpuMVM = new CpuMVM(jTextAreaMonitor,jTextAreaTrace);
        _memMVM = new MemoriaMVM();

        jPanelEscolhaPrograma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Escolha o programa:");

        jTextFieldNumeroPrograma.setText("1");

        jButtonExecutar.setText("Executar");
        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEscolhaProgramaLayout = new javax.swing.GroupLayout(jPanelEscolhaPrograma);
        jPanelEscolhaPrograma.setLayout(jPanelEscolhaProgramaLayout);
        jPanelEscolhaProgramaLayout.setHorizontalGroup(
            jPanelEscolhaProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolhaProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonExecutar)
                .addGap(28, 28, 28))
        );
        jPanelEscolhaProgramaLayout.setVerticalGroup(
            jPanelEscolhaProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolhaProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEscolhaProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNumeroPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTraces.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBoxTraceBusca.setText("Trace Busca");
        jCheckBoxTraceBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxTraceBuscaItemStateChanged(evt);
            }
        });
        jCheckBoxTraceBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTraceBuscaActionPerformed(evt);
            }
        });

        jCheckBoxTraceDecodificaExecuta.setText("Trace Decodifica/Executa");
        jCheckBoxTraceDecodificaExecuta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxTraceDecodificaExecutaItemStateChanged(evt);
            }
        });
        jCheckBoxTraceDecodificaExecuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTraceDecodificaExecutaActionPerformed(evt);
            }
        });

        jCheckBoxDumpMemoria.setText("Dump de Memória");
        jCheckBoxDumpMemoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxDumpMemoriaItemStateChanged(evt);
            }
        });
        jCheckBoxDumpMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDumpMemoriaActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Dump de Registradores");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBoxDumpPilha.setText("Dump de Pilha");
        jCheckBoxDumpPilha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxDumpPilhaItemStateChanged(evt);
            }
        });
        jCheckBoxDumpPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDumpPilhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTracesLayout = new javax.swing.GroupLayout(jPanelTraces);
        jPanelTraces.setLayout(jPanelTracesLayout);
        jPanelTracesLayout.setHorizontalGroup(
            jPanelTracesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTracesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTracesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTraceBusca)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBoxDumpPilha)
                    .addComponent(jCheckBoxTraceDecodificaExecuta)
                    .addComponent(jCheckBoxDumpMemoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTracesLayout.setVerticalGroup(
            jPanelTracesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTracesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTraceBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxTraceDecodificaExecuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDumpMemoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxDumpPilha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelConfig.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Interrupcao");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Desligar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Carregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("End.Carga:");

        jTextFieldEnderecoCarga.setText("0");

        javax.swing.GroupLayout jPanelConfigLayout = new javax.swing.GroupLayout(jPanelConfig);
        jPanelConfig.setLayout(jPanelConfigLayout);
        jPanelConfigLayout.setHorizontalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelConfigLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEnderecoCarga))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelConfigLayout.setVerticalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEnderecoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanelPlacaVideo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextAreaMonitor.setColumns(20);
        jTextAreaMonitor.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMonitor);

        jLabel2.setText("Placa vídeo");

        javax.swing.GroupLayout jPanelPlacaVideoLayout = new javax.swing.GroupLayout(jPanelPlacaVideo);
        jPanelPlacaVideo.setLayout(jPanelPlacaVideoLayout);
        jPanelPlacaVideoLayout.setHorizontalGroup(
            jPanelPlacaVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlacaVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPlacaVideoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPlacaVideoLayout.setVerticalGroup(
            jPanelPlacaVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlacaVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        jPanelHabilitaInterrupcoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBoxInterrupcoesHabilitadas.setText("Habilita interrupções");
        jCheckBoxInterrupcoesHabilitadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInterrupcoesHabilitadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHabilitaInterrupcoesLayout = new javax.swing.GroupLayout(jPanelHabilitaInterrupcoes);
        jPanelHabilitaInterrupcoes.setLayout(jPanelHabilitaInterrupcoesLayout);
        jPanelHabilitaInterrupcoesLayout.setHorizontalGroup(
            jPanelHabilitaInterrupcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabilitaInterrupcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxInterrupcoesHabilitadas)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanelHabilitaInterrupcoesLayout.setVerticalGroup(
            jPanelHabilitaInterrupcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabilitaInterrupcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxInterrupcoesHabilitadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMaximoNumeroInstrucoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Máximo número de instruções: ");

        jTextFieldMaxNumInstrucoes.setText("30");
        jTextFieldMaxNumInstrucoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaxNumInstrucoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMaximoNumeroInstrucoesLayout = new javax.swing.GroupLayout(jPanelMaximoNumeroInstrucoes);
        jPanelMaximoNumeroInstrucoes.setLayout(jPanelMaximoNumeroInstrucoesLayout);
        jPanelMaximoNumeroInstrucoesLayout.setHorizontalGroup(
            jPanelMaximoNumeroInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaximoNumeroInstrucoesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMaxNumInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanelMaximoNumeroInstrucoesLayout.setVerticalGroup(
            jPanelMaximoNumeroInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaximoNumeroInstrucoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMaximoNumeroInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaxNumInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelEnderecoCarga.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelEnderecoCargaLayout = new javax.swing.GroupLayout(jPanelEnderecoCarga);
        jPanelEnderecoCarga.setLayout(jPanelEnderecoCargaLayout);
        jPanelEnderecoCargaLayout.setHorizontalGroup(
            jPanelEnderecoCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanelEnderecoCargaLayout.setVerticalGroup(
            jPanelEnderecoCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextAreaTrace.setColumns(20);
        jTextAreaTrace.setRows(5);
        jScrollPane3.setViewportView(jTextAreaTrace);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTraces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPlacaVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelEnderecoCarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelHabilitaInterrupcoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelMaximoNumeroInstrucoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelEscolhaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelEscolhaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanelHabilitaInterrupcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelMaximoNumeroInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEnderecoCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelPlacaVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTraces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        jPanel1.getAccessibleContext().setAccessibleName("Mattos Virtual Machine");
        jPanel1.getAccessibleContext().setAccessibleDescription("Mattos Virtual Machine");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int inicio = Integer.parseInt(JOptionPane.showInputDialog("Posição de início do programa"));
        int fim = Integer.parseInt(JOptionPane.showInputDialog("Posição de fim do programa"));
        try {
            HdMVM.salvar(inicio, fim, memParm);
        } catch (IOException ex) {
            Logger.getLogger(GuiMVM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int posicao = Integer.parseInt(JOptionPane.showInputDialog("Posição onde o programa será gravado"));
        try {
            HdMVM.ler(memParm, posicao);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GuiMVM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GuiMVM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        _cpuMVM.desligar = 1;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        _cpuMVM.botao = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxDumpPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDumpPilhaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBoxDumpPilhaActionPerformed

    private void jCheckBoxDumpPilhaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxDumpPilhaItemStateChanged
        // TODO add your handling code here:
        _cpuMVM._dumpPilha = jCheckBoxDumpPilha.isSelected();
    }//GEN-LAST:event_jCheckBoxDumpPilhaItemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        _cpuMVM._dumpRegistradores = jCheckBox1.isSelected();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBoxDumpMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDumpMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDumpMemoriaActionPerformed

    private void jCheckBoxDumpMemoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxDumpMemoriaItemStateChanged
        // TODO add your handling code here:

        _cpuMVM._dumpMemoria = jCheckBoxDumpMemoria.isSelected();
    }//GEN-LAST:event_jCheckBoxDumpMemoriaItemStateChanged

    private void jCheckBoxTraceDecodificaExecutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTraceDecodificaExecutaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBoxTraceDecodificaExecutaActionPerformed

    private void jCheckBoxTraceDecodificaExecutaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxTraceDecodificaExecutaItemStateChanged
        // TODO add your handling code here:
        _cpuMVM._traceExecuta = jCheckBoxTraceDecodificaExecuta.isSelected();
    }//GEN-LAST:event_jCheckBoxTraceDecodificaExecutaItemStateChanged

    private void jCheckBoxTraceBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTraceBuscaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBoxTraceBuscaActionPerformed

    private void jCheckBoxTraceBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxTraceBuscaItemStateChanged
        // TODO add your handling code here:
        _cpuMVM._traceBuscaDecodifica = jCheckBoxTraceBusca.isSelected();
    }//GEN-LAST:event_jCheckBoxTraceBuscaItemStateChanged

    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed
        // TODO add your handling code here:

        int programa = Integer.parseInt(jTextFieldNumeroPrograma.getText());
        jTextAreaTrace.setText("");
        jTextAreaMonitor.setText("");
        int maxNumInstrucoes = Integer.parseInt(jTextFieldMaxNumInstrucoes.getText());
        _cpuMVM = new CpuMVM(jTextAreaMonitor, jTextAreaTrace);
        _cpuMVM.botao = 0;
        _cpuMVM._dumpPilha = jCheckBoxDumpPilha.isSelected();
        _cpuMVM._dumpRegistradores = jCheckBox1.isSelected();
        _cpuMVM._dumpMemoria = jCheckBoxDumpMemoria.isSelected();
        _cpuMVM._traceExecuta = jCheckBoxTraceDecodificaExecuta.isSelected();
        _cpuMVM._traceBuscaDecodifica = jCheckBoxTraceBusca.isSelected();
        _cpuMVM._interrupcoesHabilitadas = jCheckBoxInterrupcoesHabilitadas.isSelected();
        
        _cpuMVM._enderecoDeCarga = Integer.parseInt(jTextFieldEnderecoCarga.getText());

        _biosMVM = new BiosMVM(_cpuMVM, _memMVM, programa, maxNumInstrucoes,_cpuMVM._enderecoDeCarga);
    }//GEN-LAST:event_jButtonExecutarActionPerformed

    private void jCheckBoxInterrupcoesHabilitadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInterrupcoesHabilitadasActionPerformed
        // TODO add your handling code here:
        _cpuMVM._interrupcoesHabilitadas = jCheckBoxInterrupcoesHabilitadas.isSelected();
    }//GEN-LAST:event_jCheckBoxInterrupcoesHabilitadasActionPerformed

    private void jTextFieldMaxNumInstrucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaxNumInstrucoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaxNumInstrucoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GuiMVM g = new GuiMVM();
                g.jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(IMVMVersion._MVMVersion));
                //new GuiMVM().setVisible(true);
                g.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBoxDumpMemoria;
    private javax.swing.JCheckBox jCheckBoxDumpPilha;
    private javax.swing.JCheckBox jCheckBoxInterrupcoesHabilitadas;
    private javax.swing.JCheckBox jCheckBoxTraceBusca;
    private javax.swing.JCheckBox jCheckBoxTraceDecodificaExecuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelConfig;
    private javax.swing.JPanel jPanelEnderecoCarga;
    private javax.swing.JPanel jPanelEscolhaPrograma;
    private javax.swing.JPanel jPanelHabilitaInterrupcoes;
    private javax.swing.JPanel jPanelMaximoNumeroInstrucoes;
    private javax.swing.JPanel jPanelPlacaVideo;
    private javax.swing.JPanel jPanelTraces;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaMonitor;
    private javax.swing.JTextArea jTextAreaTrace;
    private javax.swing.JTextField jTextFieldEnderecoCarga;
    private javax.swing.JTextField jTextFieldMaxNumInstrucoes;
    private javax.swing.JTextField jTextFieldNumeroPrograma;
    // End of variables declaration//GEN-END:variables
}
